-- 02-seed.dev.sql — SEED DEV TEMPORAL (descartable)
-- Para tener algo que mostrar en front/back/mobile sin crear a mano.
-- Para volver a esquema limpio: borrar este archivo + `podman-compose down -v && up`.
-- Corre solo la primera vez (volumen vacío), después de 01-schema.sql.
